"""Added pdf_data column to PDFUpload

Revision ID: a6e806c90190
Revises: d6a0dd6b91be
Create Date: 2025-02-28 22:44:02.133626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e806c90190'
down_revision = 'd6a0dd6b91be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_data', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_upload', schema=None) as batch_op:
        batch_op.drop_column('pdf_data')

    # ### end Alembic commands ###
