"""added names

Revision ID: d419a80082b8
Revises: 693dfedd6a11
Create Date: 2025-06-03 12:25:20.395286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd419a80082b8'
down_revision = '693dfedd6a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption_name', sa.Text(), nullable=False))

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_name', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('summary_name')

    with op.batch_alter_table('caption', schema=None) as batch_op:
        batch_op.drop_column('caption_name')

    # ### end Alembic commands ###
